[project]
name = "t-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.120.4",
    "uvicorn[standard]>=0.38.0",
]